export const columnsFromBackend = [
  {
    title: "Sites Saved",
    items: [],
    color: "#7e22cd",
  },
  {
    title: "Opportunity",
    items: [],
    color: "#ef46e5",
  },
];

export const markers = [
  {
    id: " ID 328d4s",
    saved: "3 months ago",
    column: "Sites Saved",
    lng: -82.63932900000002,
    lat: 27.770959158362444,
    description: "Property",
    address: "400 Central Ave, Saint Petersburg, Fl, 33701",
    lotArea: "98,257 sq. ft",
    propertyState: "Mixed use",
    lastSold: "16,500,000.00",
    lastSoldDate: "04/08/2017",
    ownerShip: "CATS RED APPLE ST PETE LLC 800 3RD AVE FL 5 NEW YORK NY 10022",
    zoningBackgroundColor: "#ED75E8",
    zoningBorderColor: "#EA51E3",
    zoningTitle: "Downtown Center",
    zoningSubtitle: "Mixed Use, Saint Petersburg FL",
    zoningDate: "1/1/2022",
    fluBackgroundColor: "#f8a3b6",
    fluBorderColor: "#f58ca3",
    fluTitle: "CBD",
    fluSubtitle: "General Commercial, Saint Petersburg FL",
    fluDate: "1/1/2024",
    hazardsBackgroundColor: "",
    hazardsBorderColor: "",
    hazardsTitle: "",
    hazardsSubtitle: "",
    hazardsDate: "",
    soilBackgroundColor: "#fff",
    soilBorderColor: "#ff7f02",
    soilTitle: "Soil Survey Units",
    soilSubtitle: "Soil Survey (SSURGO), US Geological Survey",
    soilDate: "1/1/2024",
    permitsBackgroundColor: "#5fd180",
    permitsBorderColor: "#21c55e",
    permitsTitle: "233 5th St N Apartments",
    permitsSubtitle: "Approved, SWFWMD",
    permitsDate: "1/1/2024",
    waterResourcesBackgroundColor: "",
    waterResourcesBorderColor: "",
    waterResourcesTitle: "",
    waterResourcesSubtitle: "",
    waterResourcesDate: "",
    activities: [
      "You created this site",
      "Call with landowner for Site 1 at 12pm 23/05/2023",
    ],
  },
  {
    id: " ID 507f1f",
    saved: "1 week ago",
    column: "Sites Saved",
    lng: -82.62416375000001,
    lat: 27.78680025,
    description: "Property",
    address: "15TH Ave Ne, Saint Petersburg, Fl, 33704",
    lotArea: "14,618 sq. ft",
    propertyState: "Single Family",
    lastSold: "700,000.00",
    lastSoldDate: "02/21/2012",
    ownerShip: "HIGHAM GLORIA H TRUST 324 1ST AVE N SAINT PETERSBURG FL 33701",
    zoningBackgroundColor: "#ffedaa",
    zoningBorderColor: "#ffe993",
    zoningTitle: "Neighborhood Traditional Single-Family",
    zoningSubtitle: "Single Family, Saint Petersburg FL",
    zoningDate: "1/1/2022",
    fluBackgroundColor: "#fede64",
    fluBorderColor: "#ffd634",
    fluTitle: "RU",
    fluSubtitle: "Two Family, Saint Petersburg FL",
    fluDate: "1/1/2024",
    hazardsBackgroundColor: "#57c0b5",
    hazardsBorderColor: "#0fb2a4",
    hazardsTitle: "Zone AE: Coastal Floodplain",
    hazardsSubtitle: "1% Annual Chance Flood Hazard, Florida",
    hazardsDate: "1/1/2024",
    soilBackgroundColor: "#fff",
    soilBorderColor: "#ff7f02",
    soilTitle: "Soil Survey Units",
    soilSubtitle: "Soil Survey (SSURGO), US Geological Survey",
    soilDate: "1/1/2024",
    permitsBackgroundColor: "",
    permitsBorderColor: "",
    permitsTitle: "",
    permitsSubtitle: "",
    permitsDate: "",
    waterResourcesBackgroundColor: "",
    waterResourcesBorderColor: "",
    waterResourcesTitle: "",
    waterResourcesSubtitle: "",
    waterResourcesDate: "",
    activities: ["Call with landowner for Site 1 at 12pm 23/05/2023"],
  },
  {
    id: " ID 468r9j",
    saved: "3 days ago",
    column: "Opportunity",
    lng: -82.48887657335295,
    lat: 28.25511984288235,
    description: "Property",
    address: "Land O Lakes, Fl, 34638",
    lotArea: "3,750,883.95 sq. ft",
    propertyState: "Agriculture",
    lastSold: "780,000",
    lastSoldDate: "14/07/2018",
    ownerShip: "SK DEERBROOK LLC 105 NE 1ST ST DELRAY BEACH FL 33444",
    zoningBackgroundColor: "#62e684",
    zoningBorderColor: "#1cdf63",
    zoningTitle: "Agricultural",
    zoningSubtitle: "Agriculture, Pasco County FL",
    zoningDate: "1/1/2022",
    fluBackgroundColor: "#ffedaa",
    fluBorderColor: "#ffe993",
    fluTitle: "RES-3",
    fluSubtitle: "Single Family, Pasco County FL",
    fluDate: "1/1/2024",
    hazardsBackgroundColor: "#57c0b5",
    hazardsBorderColor: "#0fb2a4",
    hazardsTitle: "Zone A",
    hazardsSubtitle: "1% Annual Chance Flood Hazard, Florida",
    hazardsDate: "1/1/2024",
    soilBackgroundColor: "#fff",
    soilBorderColor: "#ff7f02",
    soilTitle: "Soil Survey Units",
    soilSubtitle: "Soil Survey (SSURGO), US Geological Survey",
    soilDate: "1/1/2024",
    permitsBackgroundColor: "#5ed07f",
    permitsBorderColor: "#21c55e",
    permitsTitle: "Bexley Road/Wisteria Loop Vision Road",
    permitsSubtitle: "Approved, SWFWMD",
    permitsDate: "1/1/2024",
    waterResourcesBackgroundColor: "#7949ed",
    waterResourcesBorderColor: "#580fe9",
    waterResourcesTitle: "Known Well",
    waterResourcesSubtitle: "Known Well, Pasco County FL",
    waterResourcesDate: "1/1/2023",
    activities: ["Meeting on Wednesday to see the property"],
  },
];
